[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200


solc_version = "0.8.30"

remappings= [
    '@openzeppelin=lib/openzeppelin-contracts',
    '@forge-std=lib/forge-std/src',
    '@contract=src',
    '@test=test',
    '@interface=src/interfaces'
]


# Test config
[fuzz]
runs = 256

# Celo network config
[rpc_endpoints]
alfajores = "https://alfajores-forno.celo-testnet.org"
celo = "https://forno.celo.org"

[etherscan]
alfajores = { key = "${ETHERSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
celo = { key = "${ETHERSCAN_API_KEY}", url = "https://api.celoscan.io/api" }